### ISSUE TITLE
about adding Gaussian noise in defense.py used in the demos

### ISSUE THREAD

**Issue by h2th3k** [illidanlab/inversion-influence-function#1]
Hello, I'd like to check at the following line:
 https://github.com/illidanlab/inversion-influence-function/blob/main/defense.py#L110C13-L110C61
shouldn't it be used as:
```python
for i, input_grad in enumerate(input_gradient):
    input_gradient[i] = input_grad + noise[i] 
```

**Comment by haobozhang** [comment]
Hi @h2th3k , sorry for the late reply.

Thanks for your comment! I think it shouldn't cause any issues with the original code. Could you please provide more information and also the error info? Thanks!
